### ISSUE TITLE
IMPORTANT: too much specificity

### ISSUE THREAD

**Issue by DutchPete** [kinmury/Golden-Book#14]
You theme is full of `!important` and much too specificities. Don't ask me for details about the latter, I was told by someone who knows way more about CSS than I do.

What I can tell you is that I ran a couple of times into an issue whereby, while customizing, certain CSS code that works in other themes does not work in yours, and it had to be made more specific.

Example: I wanted to changed the size of the headers in Edit. Normally this works:

```css
.cm-header-1 {
font-size: 28px;
}
```

Not in your theme.
This is what I had to do:
```css
.cm-s-obsidian .cm-header-1.cm-header-1 {
    font-size: 28px !important;
}
```

Notice the 1st line is way more specific, and I had to add an `!important`, even though that is normally superfluous.
